DROP TABLE IF EXISTS DOMICILIOS;
CREATE TABLE DOMICILIOS (
ID INT AUTO_INCREMENT PRIMARY KEY,
CALLE VARCHAR(100),
NUMERO VARCHAR (20),
LOCALIDAD VARCHAR (20),
PROVINCIA VARCHAR(20));

DROP TABLE IF EXISTS PACIENTES;
CREATE TABLE PACIENTES (
ID INT AUTO_INCREMENT PRIMARY KEY,
APELLIDO VARCHAR (100),
NOMBRE VARCHAR (100),
DOCUMENTO VARCHAR (100),
FECHA_INGRESO DATE,
DOMICILIO_ID INT,
EMAIL VARCHAR(100)
ODONTOLOGO_ID INT);

DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS (
ID INT AUTO_INCREMENT PRIMARY KEY,
APELLIDO VARCHAR (100),
NOMBRE VARCHAR (100),
MATRICULA VARCHAR (100));


INSERT INTO DOMICILIOS (CALLE, NUMERO, LOCALIDAD, PROVINCIA)
VALUE ('calle a','418','Salta Capital','Salta');

INSERT INTO PACIENTES (APELLIDO, NOMBRE, DOCUMENTO, FECHA_INGRESO, DOMICILIO_ID, EMAIL)
VALUE ('Perez','Camila','38795559','2023-04-16',1,'cp@gmail.com');

INSERT INTO ODONTOLOGOS (APELLIDO, NOMBRE, MATRICULA)
VALUE ('Rodriguez','Josefa','MD1234');


